[infra] task: updated dockerfile, fixed setup_java, minor fixes
NemProject/nem pull request #173
Opened 2022-11-21 21:29 UTC by yilmazbahadir

Problem: 
- Dockerfile needed for containerization 
- Lack of cross environment support in `setup_java9.sh`

Solution: 
- Updated Dockerfile for multistage build, added user w/ UID and UNAME args and fixed the issues
- ~~Updated `setup_java9.sh` file for mac env support~~ Removed setup_java9.sh files and upgraded min Java version to 11.
- Minor fixes
- Fixed failing unit tests in `HttpMethodClientTest`

2022-11-24 15:11 UTC, gimre-xymcity requested changes
this change should be slightly larger:
 * we should change default compilation to java 11 (especially, that jre installed is == 11
 * and as a fallback: java8

2022-11-24 15:11 UTC, gimre-xymcity commented on infra/docker/Dockerfile
> +  && cd nem
that last cd isn't really needed

2022-11-28 11:04 UTC, yilmazbahadir commented
> this change should be slightly larger:
> 
> * we should change default compilation to java 11 (especially, that jre installed is == 11
> * and as a fallback: java8

sure, I'm on it now.

2022-11-28 21:51 UTC, yilmazbahadir commented on infra/docker/Dockerfile
> +  && cd nem
fixed

2022-11-28 21:54 UTC, yilmazbahadir commented
As discussed in the discord channel, updated the min required Java SDK version to 11 and applied related updates in Readme files, CI scripts, pom.xml's and the dockerfile.

2022-11-28 21:57 UTC, yilmazbahadir commented on deploy/src/main/java/org/nem/deploy/NemFormatter.java
> -		record.setMillis(TIME_PROVIDER.getNetworkTime().getRaw() + SystemTimeProvider.getEpochTimeMillis() - TIME_ZONE_OFFSET);
since `setMillis` method was deprecated, replaced it with `setInstant` as suggested.

2022-12-06 14:41 UTC, gimre-xymcity approved these changes
I was wondering if we should have fallback to java8 _somewhere_ but change itself is good so 👍

2022-12-06 16:40 UTC, merged