[infra] feat: jenkins docker build and publish integration
NemProject/nem pull request #191
Opened 2022-12-17 20:44 UTC by yilmazbahadir

2022-12-19 20:52 UTC, Wayonb requested changes

2022-12-19 20:52 UTC, Wayonb commented on infra/Dockerfile
> +  && git clone https://github.com/NemProject/nem.git \
``git clone https://github.com/NemProject/nem.git -b $GIT_BRANCH_NAME

2022-12-20 09:53 UTC, yilmazbahadir commented on infra/Dockerfile
> +  && git clone https://github.com/NemProject/nem.git \
done 👍

2023-01-03 15:34 UTC, yilmazbahadir commented
superseded by https://github.com/NemProject/nem/pull/196

2023-01-03 15:34 UTC, closed without merging