[nis] feat: jenkins docker build, publish integration
NemProject/nem pull request #196
Opened 2022-12-26 12:47 UTC by yilmazbahadir

An alternative(probably better) approach to https://github.com/NemProject/nem/pull/191.

What was the issue?
- in https://github.com/NemProject/nem/pull/191 dockerfile was pulling from remote repo, we weren't successful to pass the current branch to the dockerfile.
- it was adding a new jenkins job to the multi-branch jenkins job which was running in any case therefore causing a performance hit.
- In our discussions with @Wayonb we agreed that this can cause issues, better to build from workspace as it's been done for `symbol/rest`.

What's the fix?
- Created an alternative Dockerfile in the `nis` module, which is copying the code from the jenkins workspace _using the current branch_ which will allow us to push images from feature branches for testing. (the same way as `symbol/rest` was configured`)
- Docker publish parameters are placed inside `nis/Jenkinsfile` thus we'll utilize the current job and we won't need to create any other Job like we did in https://github.com/NemProject/nem/pull/191, which puts an overhead to the Jenkins job even we don't publish any docker images.

2023-01-03 15:10 UTC, Wayonb requested changes

2023-01-03 15:10 UTC, Wayonb commented on nis/Dockerfile
> +CMD ["bash", "-c", "java -Xms${MEMORY_MS} -Xmx${MEMORY_MX} -cp /usersettings:./nis/*:./libs/* org.nem.deploy.CommonStarter"]
missing new line at the end of file

2023-01-03 15:10 UTC, Wayonb commented on nis/Jenkinsfile
> +    publisher = 'docker'
spacing

2023-01-03 15:10 UTC, Wayonb commented on nis/Jenkinsfile
> +    dockerBuildArgs = "-f ./Dockerfile  ./../"
maybe this? dockerBuildArgs = "-f Dockerfile .."

2023-01-03 15:26 UTC, gimre-xymcity approved these changes
approving, assuming comments from wayon

2023-01-03 20:35 UTC, yilmazbahadir commented
@Wayonb comments should be fixed and also updated the nis/README.md for the docker instructions.

2023-01-04 03:12 UTC, Wayonb approved these changes

2023-01-04 07:34 UTC, merged